# Generated by Django 2.0.7 on 2018-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizMania', '0002_questions_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='answeredQuestions',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
