# Generated by Django 2.0.7 on 2018-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizMania', '0004_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questionImage',
            field=models.ImageField(blank=True, null=True, upload_to='.'),
        ),
    ]
