# Generated by Django 2.0.7 on 2018-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizMania', '0006_auto_20180801_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_code', models.CharField(max_length=50)),
                ('road_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('officer_id', models.IntegerField(default=0)),
                ('lat1', models.FloatField(default=0)),
                ('lon1', models.FloatField(default=0)),
                ('lat2', models.FloatField(default=0)),
                ('lon2', models.FloatField(default=0)),
            ],
        ),
    ]
