# Generated by Django 2.0.7 on 2018-08-25 05:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizMania', '0007_roadmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('road', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
