# Generated by Django 2.0.7 on 2018-08-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizMania', '0008_roads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roads',
            name='area',
        ),
        migrations.AddField(
            model_name='roads',
            name='discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
