# Generated by Django 2.0.7 on 2018-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizMania', '0003_auto_20180729_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleString', models.CharField(max_length=2000)),
            ],
        ),
    ]
