# Generated by Django 2.0.7 on 2018-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizMania', '0005_auto_20180731_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
